// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftwykhmauasmxpygshnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0d3lraG1hdWFzbXhweWdzaG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NjE4MjUsImV4cCI6MjA2NzMzNzgyNX0.-py2GYp-lSSc-Iz2iIsrgSrZpCHM7zubAaTZWt-bQfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});